FROM nginx:1.27-alpine

LABEL maintainer="tu@email.com"
LABEL description="Nginx optimizado para WordPress de alto rendimiento"

# Eliminamos la configuración por defecto de Nginx para usar la nuestra
RUN rm /etc/nginx/conf.d/default.conf

# Ajustamos los límites del sistema operativo para manejar muchas conexiones
RUN echo "nginx soft nofile 65535" >> /etc/security/limits.conf && \
    echo "nginx hard nofile 65535" >> /etc/security/limits.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]